// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDceopqUbGmuorsZV5LqiHFRCe9Gohxrmo',
    appId: '1:887653938327:android:ed1f05aeeffe1b623f65d2',
    messagingSenderId: '887653938327',
    projectId: 'studymate-acbf8',
    storageBucket: 'studymate-acbf8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo0MqCfoyTV7N2B9h-ugQ99Kh4xL6Yfps',
    appId: '1:887653938327:ios:02311869c3983b7c3f65d2',
    messagingSenderId: '887653938327',
    projectId: 'studymate-acbf8',
    storageBucket: 'studymate-acbf8.firebasestorage.app',
    iosBundleId: 'com.example.studyMate',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiEj8vjSsJT9R4oAWceMfsx4RiWso8qTo',
    appId: '1:887653938327:web:00f080d53bd2b0753f65d2',
    messagingSenderId: '887653938327',
    projectId: 'studymate-acbf8',
    authDomain: 'studymate-acbf8.firebaseapp.com',
    storageBucket: 'studymate-acbf8.firebasestorage.app',
    measurementId: 'G-1ZC59P816F',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo0MqCfoyTV7N2B9h-ugQ99Kh4xL6Yfps',
    appId: '1:887653938327:ios:02311869c3983b7c3f65d2',
    messagingSenderId: '887653938327',
    projectId: 'studymate-acbf8',
    storageBucket: 'studymate-acbf8.firebasestorage.app',
    iosBundleId: 'com.example.studyMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiEj8vjSsJT9R4oAWceMfsx4RiWso8qTo',
    appId: '1:887653938327:web:bf808f7d5286520b3f65d2',
    messagingSenderId: '887653938327',
    projectId: 'studymate-acbf8',
    authDomain: 'studymate-acbf8.firebaseapp.com',
    storageBucket: 'studymate-acbf8.firebasestorage.app',
    measurementId: 'G-83XB0JYSH4',
  );

}